version: '3.9'

services:
  nest:
     container_name: nest_app
     image: danywalls/nest-api:latest
     restart: always
     environment:
       DB_HOST: 'db'
       DB_USER: 'root'
       DB_PASS: 'example'
       DB_NAME: 'example'
     ports:
       - "3000:3000"
     depends_on:
       - db
  db:
    image: mysql
    container_name: api-db
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_DATABASE: 'example'
    ports:
      - "3306:3306"